backend = "xrender";
use-damage = true;

shadow = false;
fading = false;

corner-radius = 8;
rounded-corners-exclude = [
  "window_type = 'desktop'",
  "window_type = 'dock'"
];

active-opacity = 1.0;
inactive-opacity = 1.0;
frame-opacity = 1.0;
inactive-opacity-override = false;

blur-background = false;
blur-background-frame = false;
blur-background-fixed = false;
blur-method = "none";

detect-client-opacity = true;
unredir-if-possible = true;
