backend = "glx";
use-damage = true;

shadow = false;
fading = false;

active-opacity = 1.0;
inactive-opacity = 1.0;
frame-opacity = 1.0;
inactive-opacity-override = false;

opacity-rule = [
  "97:class_g = 'kitty'",
  "97:class_g = 'Spotify'",
  "97:class_g = 'spotify'"
];

blur-background = true;
blur-background-frame = true;
blur-background-fixed = true;
blur: {
  method = "dual_kawase";
  strength = 7;
  size = 0;
};
blur-background-exclude = [
  "!(class_g = 'kitty' || class_g = 'Spotify' || class_g = 'spotify')"
];

detect-client-opacity = true;
unredir-if-possible = true;
