# /etc/optimus-manager/optimus-manager.conf.
# BIOS in Hybrid mode.

[optimus]
startup_mode=hybrid
switching=none
pci_power_control=yes

[intel]
driver=modesetting

[nvidia]
dynamic_power_management=fine
modeset=yes
